name: Super-Linter

on:
  push

jobs:
  super-lint:
    runs-on: ubuntu-latest  # Change "macos-latest" to "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
